#!/usr/bin/env python

import os

class bcolors:
    ENDC      = '\033[0m'
    BOLD      = '\033[1m'
    UNDERLINE = '\033[4m'
    INVERSE   = '\033[7m'

print bcolors.INVERSE + "Warning: No active frommets remain. Continue?" + bcolors.ENDC

history_dict = {}
with open(os.path.join(os.path.expanduser('~'),'.bash_history')) as f:
    for line in f:
        chomped = line.rstrip()
        if history_dict.get(chomped):
            history_dict[chomped] += 1
        else:
            history_dict[chomped] = 1

for cmd, cnt in history_dict.iteritems():
    print "%s %-100s" % (cmd, cnt)

# sort by count
