#!/usr/bin/env python

import os

class bcolors:
    ENDC      = '\033[0m'
    BOLD      = '\033[1m'
    UNDERLINE = '\033[4m'
    INVERSE   = '\033[7m'

print bcolors.INVERSE + "Warning: No active frommets remain. Continue?" + bcolors.ENDC

history_dict = {}
with open(os.path.join(os.path.expanduser('~'),'.bash_history')) as f:
    for line in f:
        if history_dict.get(line):
            history_dict[line] += 1
        else:
            history_dict[line] = 1


from pprint import *

pprint(history_dict)
